GET http://localhost:3500/subscribers

###
GET http://localhost:3500/subscribers/1556

###
POST http://localhost:3500/subscribers
Content-Type: application/json

{
    "name":"Amazing Person",
    "subscribedToChannel":"Web De Simplified"
}