GET http://localhost:4000/subscribers

###
GET http://localhost:4000/subscribers/1556

###
POST http://localhost:4000/subscribers
Content-Type: application/json

{
    "name":"Amazing Person",
    "subscribedToChannel":"Web De Simplified"
}